version: "3.9"

volumes:
  postgres-data:
  models-cache:

services:
  ml:
    build:
      context: "python-backend/"
      dockerfile: "Dockerfile"
    restart: "always"
    volumes:
      - "models-cache:/.cache/huggingface/hub/"
    ports:
      - "10000:10000"
    command: ["python3", "server.py"]
  db:
    image: "pgvector/pgvector:pg16"
    restart: "always"
    env_file:
      - ".env"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  # mongo:
  #   image: "mongo:5.0"
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
  #     MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"
  #   volumes:
  #     - "mongo-data:/data/db"
  #   ports:
  #     - "27017:27017"

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_USER}"
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASS}"
  #     ME_CONFIG_MONGODB_URL: mongodb://"${MONGO_USER}":"${MONGO_PASS}"@mongo:27017/
