version: "3.9"

volumes:
  pg_data:
  redis_data:
  logs:

services:
  pg:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=dev
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  server:
    build:
      context: ./go-backend
      dockerfile: Dockerfile
      target: prod
    image: purple
    depends_on:
      - pg
      - redis
    ports:
      - "9999:9999"
    command: ./main
    volumes:
      - ./go-backend/logs:/logs
