version: "3.9"

volumes:
  pg_data:
  models-cache:
  logs:

services:
  search-engine:
    build:
      context: ./python-backend
      dockerfile: Dockerfile
    environment:
      - PG_CONN_STR=${PG_CONN_STR}
      - MONGO_CONN_STR=${MONGO_CONN_STR}
      - OLLAMA_API=${OLLAMA_API}
    restart: always
    volumes:
      - models-cache:/root/.cache/huggingface/hub/
    ports:
      - "10000:10000"
    command: [ "python3", "server.py" ]

  pg:
    image: pgvector/pgvector:pg15
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  go-backend:
    build:
      context: ./go-backend
      dockerfile: Dockerfile
    image: purple
    depends_on:
      - pg
      - search-engine
    ports:
      - "9999:9999"
    command: ./main
    volumes:
      - ./go-backend/logs:/logs

  # mongo:
  #   image: "mongo:5.0"
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
  #     MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"
  #   volumes:
  #     - "mongo-data:/data/db"
  #   ports:
  #     - "27017:27017"

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_USER}"
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASS}"
  #     ME_CONFIG_MONGODB_URL: mongodb://"${MONGO_USER}":"${MONGO_PASS}"@mongo:27017/