server:
  port: 9999
  logLevel: "debug"
  corsOrigins: "http://localhost:3000"

postgres:
  user: "pguser"
  password: "pgpass"
#  host: "pg"
  host: "localhost"
  port: 5432
  db: "dev"
  ssl: false

searchEngine:
#  host: "search-engine"
  host: "localhost"
  port: 10000
