definitions:
  domain.LoginReq:
    properties:
      email:
        type: string
      password:
        maxLength: 20
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  domain.SignupReq:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        maxLength: 20
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  response.ErrorResponse:
    properties:
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Validate credentials and set cookie if valid
      parameters:
      - description: User's credentials
        in: body
        name: loginReq
        required: true
        schema:
          $ref: '#/definitions/domain.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: User successfully logged in
          schema:
            type: string
        "401":
          description: Invalid password
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "422":
          description: Body validation error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Login
      tags:
      - auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Adds new user to DB; email and password are required
      parameters:
      - description: User's data to signup
        in: body
        name: signupReq
        required: true
        schema:
          $ref: '#/definitions/domain.SignupReq'
      produces:
      - application/json
      responses:
        "201":
          description: User successfully created
          schema:
            type: string
        "400":
          description: Password is too long
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "422":
          description: Body validation error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Signup
      tags:
      - auth
swagger: "2.0"
