# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import search_engine_pb2 as search__engine__pb2


class SearchEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Respond = channel.unary_unary(
                '/search_engine.SearchEngine/Respond',
                request_serializer=search__engine__pb2.Query.SerializeToString,
                response_deserializer=search__engine__pb2.Response.FromString,
                )


class SearchEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Respond(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Respond': grpc.unary_unary_rpc_method_handler(
                    servicer.Respond,
                    request_deserializer=search__engine__pb2.Query.FromString,
                    response_serializer=search__engine__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'search_engine.SearchEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SearchEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Respond(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/search_engine.SearchEngine/Respond',
            search__engine__pb2.Query.SerializeToString,
            search__engine__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
