# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search_engine.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13search_engine.proto\x12\rsearch_engine\"$\n\x05Query\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\")\n\x08Response\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t2\x8e\x01\n\x0cSearchEngine\x12:\n\x07Respond\x12\x14.search_engine.Query\x1a\x17.search_engine.Response\"\x00\x12\x42\n\rRespondStream\x12\x14.search_engine.Query\x1a\x17.search_engine.Response\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_engine_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUERY']._serialized_start=38
  _globals['_QUERY']._serialized_end=74
  _globals['_RESPONSE']._serialized_start=76
  _globals['_RESPONSE']._serialized_end=117
  _globals['_SEARCHENGINE']._serialized_start=120
  _globals['_SEARCHENGINE']._serialized_end=262
# @@protoc_insertion_point(module_scope)
